spring:
    #QDP库
    datasource:
        name: dataSource
        #continue-on-error: true
        url: jdbc:mysql://127.0.0.1:3306/wwtg_qdp?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        #type: com.alibaba.druid.pool.DruidDataSource 
        driver-class-name: com.mysql.jdbc.Driver 
#       filters: stat
        maxActive: 20
        initialSize:  1
        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    #jpa:
    #     packageToScan: 
    #    showSql: true
    #    hibernate: 
    #      ddl-auto: update
    #正式业务库
    datasource1:
        name: dataSource1
        url: jdbc:mysql://localhost:3306/wwtg?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver 
    #jpa1: 
     #   packageToScan: com.mr.sm.entity.datasource1.*
    #    showSql: true
        
    devtools:
      restart:
        additional-exclude: com/**
    tomcat:
      uri-encoding: UTF-8
    http:
      encoding:
        charset: UTF-8
        force: true
        enabled: true
 
server:
        port: 8080
        servlet: 
            context-path: /qdp
 
project:
        #项目名称
        name: wwtg 
        #框架
        framework: bdf3
        #应用名称
        appName: wwtg
        #包名前缀
        packagePrefix: wwtg
        #公司名
        company: mr
        #工作空间
        # workspace: C:\Users\14090284\eclipse-workspace\wwtg
        workspace: C:\Users\14090284\eclipse-workspace\wwtg